### ISSUE TITLE
Training GCN with Cora Dataset

### ISSUE THREAD

**Issue by Salmaafifi98** [camlsys/degree-quant#9]
Thank you so much for posting the code! 

I am just facing a lot of issues trying to extend your code for GCNs. I created a file for gcn.py similar to gin.py and passed the in and out channels for GCN accordingly and adjusted the dataset. I am now getting an error regarding the keyword "weights_low" as follows:

Traceback (most recent call last):
  File "degree/reddit_binary/main.py", line 109, in <module>
Namespace(DQ=True, batch_size=128, change=0.1, epochs=200, fp32=False, gc_abs=False, gc_mom=False, gc_per=True, hidden=64, int4=False, int8=True, low=0.0, lr=0.005, lr_decay_factor=0.5, lr_decay_step_size=50, noise=1.0, num_layers=5, outdir='./run', path='./data', sample_prop=None, ste_abs=False, ste_mom=False, ste_per=False, wd=0.0002)
Generating ProbabilisticHighDegreeMask: {'prob_mask_low': 0.0, 'prob_mask_change': 0.1}
    model = GCN(
  File "/content/degree/reddit_binary/gcn.py", line 134, in __init__
    self.conv1 = gcn_layer(
  File "/content/degree/dq/multi_quant.py", line 247, in __init__
    self.reset_parameters()
  File "/content/degree/dq/multi_quant.py", line 259, in reset_parameters
    self.layer_quantizers[key] = self.layer_quant_fns[key]()
KeyError: 'weights_low'

Can you please help with this?

**Comment by Waleed794** [comment]
Hi @Salmaafifi98 were you able to replicate the results from the paper?
